# _config.yml

# 사이트 상단(혹은 브라우저 탭)에 표시되는 타이틀. 비워두면 로고/텍스트 출력 X
title: ""

# 사이트 설명 (SEO 등에서 사용)
description: ""

# 사이트 저자명
author: "Jinsung Kim"

# 아바타(프로필 사진) 경로. 필요 없으면 제거 가능
avatar: /logo.png

# 이메일
email: kimjinsung8290@naver.com

# 사용 중인 플러그인 (jekyll-feed 제거)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# 한 페이지당 포스트 개수
paginate: 10

# 언어 설정
lang: en

# 테마 스킨(다크)
skin: midnight

# 사이트 URL (커스텀 도메인 또는 GitHub Pages 주소 사용 가능)
url: ""

# 소셜 미디어 (GitHub만 남기고 Subscribe, Twitter 등 제거)
social:
  name: "Jinsung Kim"
  links:
    - "https://github.com/KimJinSungDataScientist"

# 빌드에서 제외할 항목
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# 필요한 경우 Google Analytics, Disqus 설정
# google_analytics:
# disqus:
